### ISSUE TITLE
Bug: stream error: stream ID x; INTERNAL_ERROR is not handled

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#21]
The following error can be thrown, but should be handled:

```
error getting file events for ffs query: main_query
panic: stream error: stream ID 2223; INTERNAL_ERROR

goroutine 32318 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc000116c90, 0xa, 0xc0000fc580, 0x17, 0xc000116ca0, 0xf, 0xc000116c9a, 0x2, 0xc000116c9c, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:233 +0x1d6a
created by github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery.func5
        /app/ffsEvent/ffsEvent.go:180 +0x206
```

**Comment by BenB196** [comment]
Fixed in release [v0.1.1](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.1.1).
