### ISSUE TITLE
Bug: App fails to start if the inProgressQueries file is empty but exists

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#22]
If the inProgressQueries files exists, the app will fail to start with the following error:

```
error getting old in progress queries
panic: error: parsing in progress queries from: /crashplan-ffs-puller/<query_name>inProgressQueries.json unexpected end of JSON input

goroutine 18 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery(0xc000130600, 0x39, 0xc00005a070, 0x6b, 0xc000122e00, 0x1, 0x4, 0x1, 0x1f90, 0xc000026cf0, ...)
        /app/ffsEvent/ffsEvent.go:44 +0x10f5
created by main.main.func1
        /app/main.go:46 +0x15f
```

**Comment by BenB196** [comment]
Fixed in releease [v0.0.7](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.0.7).
