### ISSUE TITLE
Bug: 500 Internal Server Error should be properly handled

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#30]
The following error should not result in a panic, instead it should result in the query being retried. A max of 10 retries should be allowed until a fatal error/panic is thrown. This limit is to prevent the program from building up a massive queue of in progress/failed queries which will eventually become impossible to handle.

```
error getting file events for ffs query: main_query
panic: Error with gathering file events POST: 500 Internal Server Error

goroutine 191656 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc00012ed90, 0xa, 0xc00010c660, 0x17, 0xc00012eda0, 0xf, 0xc00012ed9a, 0x2, 0xc00012ed9c, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:234 +0x2802
created by github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery.func5
        /app/ffsEvent/ffsEvent.go:184 +0x1d5
```

**Comment by BenB196** [comment]
Fixed in release [v0.1.1](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.1.1).
