### ISSUE TITLE
Bug: Handle 400 Bad Request

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#33]
The following is not handled but should be:

```
error getting file events for ffs query: main_query
panic: Error with gathering file events POST: 400 Bad Request

goroutine 144713 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc000025390, 0xa, 0xc000022a00, 0x17, 0xc0000253a0, 0xf, 0xc00002539a, 0x2, 0xc00002539c, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:249 +0x2c05
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc000025390, 0xa, 0xc000022a00, 0x17, 0xc0000253a0, 0xf, 0xc00002539a, 0x2, 0xc00002539c, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:241 +0x281d
created by github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery.func5
        /app/ffsEvent/ffsEvent.go:185 +0x1e9
```

**Comment by BenB196** [comment]
Fixed in release [v0.1.2](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.1.2).
