### ISSUE TITLE
Bug: Handle stream error: stream ID x; PROTOCOL_ERROR

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#39]
The following error is not properly handled, and should result in retry attempts.

```
panic: stream error: stream ID x; PROTOCOL_ERROR

goroutine 225026 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc000027390, 0xa, 0xc000022a00, 0x17, 0xc0000273a0, 0xf, 0xc00002739a, 0x2, 0xc00002739c, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:251 +0x2cdf
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc000027390, 0xa, 0xc000022a00, 0x17, 0xc0000273a0, 0xf, 0xc00002739a, 0x2, 0xc00002739c, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:243 +0x282f
created by github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery.func5
        /app/ffsEvent/ffsEvent.go:185 +0x1e9
```

**Comment by BenB196** [comment]
Fixed in release [v0.1.3](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.1.3).
