### ISSUE TITLE
Bug: Handle unexpected EOF

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#45]
The following error is not properly handled.

```
error getting file events for ffs query: main_query
panic: Post https://forensicsearch-default.prod.ffs.us2.code42.com/forensic-search/queryservice/api/v1/fileevent/export: unexpected EOF

goroutine 605928 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc000128d90, 0xa, 0xc0000f6660, 0x17, 0xc000128da0, 0xf, 0xc000128d9a, 0x2, 0xc000128d9c, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:251 +0x2d3b
created by github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery.func5
        /app/ffsEvent/ffsEvent.go:185 +0x1e9
```

**Comment by BenB196** [comment]
Fixed in release [v0.1.5](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.1.5).
