### ISSUE TITLE
Bug: Handle POST: 504 Gateway Timeout

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#62]
See error below:

```
panic: Error with gathering file events POST: 504 Gateway Timeout

goroutine 67027614 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc000024df0, 0xa, 0xc000022420, 0x17, 0xc000024e00, 0xf, 0xc000024dfa, 0x2, 0xc000024dfc, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:251 +0x3878
created by github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery.func5
        /app/ffsEvent/ffsEvent.go:185 +0x205
```

**Comment by BenB196** [comment]
Fixed in release [v0.1.9](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.1.9).
