### ISSUE TITLE
Bug: Handle panic: record on line x: wrong number of fields

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#72]
The following panic should instead of retried:

```
panic: record on line 6161: wrong number of fields

goroutine 10680229 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc000024df0, 0xa, 0xc000022720, 0x17, 0xc000024e00, 0xf, 0xc000024dfa, 0x2, 0xc000024dfc, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:215 +0x3b73
created by github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery.func3
        /app/ffsEvent/ffsEvent.go:139 +0x205
```

**Comment by BenB196** [comment]
Fixed in release [v0.2.1](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.2.1).
