### ISSUE TITLE
Bug: Handle record on line x; parse error on line x, column x: extraneous or missing " in quoted-field

### ISSUE THREAD

**Issue by BenB196** [BenB196/crashplan-ffs-puller#76]
The following error is not handled, but it should be:

panic: record on line 1849; parse error on line 1851, column 0: extraneous or missing " in quoted-field

goroutine 70821029 [running]:
github.com/BenB196/crashplan-ffs-puller/ffsEvent.queryFetcher(0xc00012add0, 0xa, 0xc00012c400, 0x17, 0xc00012ade0, 0xf, 0xc00012adda, 0x2, 0xc00012addc, 0x3, ...)
        /app/ffsEvent/ffsEvent.go:215 +0x3c41
created by github.com/BenB196/crashplan-ffs-puller/ffsEvent.FFSQuery.func3
        /app/ffsEvent/ffsEvent.go:139 +0x205

**Comment by BenB196** [comment]
Fixed in release [v0.2.2](https://github.com/BenB196/crashplan-ffs-puller/releases/tag/v0.2.2)
